// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jldadxkmhjhpunnsuckm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsZGFkeGttaGpocHVubnN1Y2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDQ5NzYsImV4cCI6MjA2MjcyMDk3Nn0.ClpOX97WyVqD_hswmTroDOCC7Af9RHFvIbGLcB8nICA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);